import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import {tools} from './catalog.mjs';
import {renderGuide} from './content.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin=process.env.SITE_URL||'https://devtoolshub-beta.vercel.app';
if(origin&&!/^https:\/\/[a-zA-Z0-9.-]+(?::\d+)?\/?$/.test(origin))throw Error('SITE_URL must be an HTTPS origin.');
await mkdir('dist',{recursive:true});
const footer='<footer><span>DevToolsHub · Free tools for everyday development.</span><nav><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></nav></footer>';
function page(title,description,body,path='',id='') {return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+' | DevToolsHub</title><meta name="description" content="'+esc(description)+'"><meta name="theme-color" content="#2853df"><meta name="google-site-verification" content="Gf27z1D45mq-hTV8bLPyQR1ifGuvOI7qiSrOoBfyG9A">'+(origin?'<link rel="canonical" href="'+esc(origin.replace(/\/$/,'')+'/'+path)+'">':'')+'<link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"><script type="module" src="/app.mjs"></script></head><body data-tool="'+id+'"><a class="skip" href="#main">Skip to content</a><header><div class="top"><a class="brand" href="/"><span>&lt;/&gt;</span>DevToolsHub</a><nav aria-label="Main navigation"><a href="/">All tools</a><a href="/about">About</a><a href="https://github.com/PrasannaArise/devtoolshub">GitHub ↗</a></nav></div></header><div class="layout"><aside><div class="eyebrow">Your toolbox</div><nav aria-label="Developer tools">'+tools.map(t=>'<a href="/'+t.id+'"'+(id===t.id?' aria-current="page"':'')+'><span class="mini-icon">'+esc(t.icon)+'</span>'+esc(t.name.replace(' / Decoder','').replace(' Encoder','').replace('Unix Timestamp Converter','Timestamp Converter'))+'</a>').join('')+'</nav><p class="local-note">Runs in your browser.<br>Your tool inputs stay on this device. No signup needed.</p></aside><main id="main">'+body+footer+'</main></div></body></html>';}
await writeFile('dist/index.html',page('Free Developer Tools','Ten free browser-based developer tools for JSON, JWT, Base64, UUID, timestamps, URLs, cron, regex, SQL, and hashes.','<div class="intro-row"><div><div class="eyebrow">Less busywork. More building.</div><h1>Your everyday developer toolkit.</h1></div><span class="badge">10 tools · No signup</span></div><p class="intro">Format, decode, convert, and debug. Quick utilities that keep your data in your browser.</p><label for="search" class="eyebrow">Find a tool</label><input class="search" id="search" type="search" placeholder="Search tools, e.g. JSON or encoding" autocomplete="off"><div class="search-status" id="search-status" role="status">10 tools available</div><section class="cards" aria-label="All developer tools">'+tools.map(t=>'<a data-card class="card" href="/'+t.id+'"><div class="card-top"><span class="icon">'+esc(t.icon)+'</span><span class="category">'+t.category+'</span></div><h2>'+t.name+'</h2><p>'+t.description+'</p></a>').join('')+'</section>'));
for(const t of tools){const body='<div class="breadcrumb"><a href="/">All tools</a> / '+t.category+'</div><div class="intro-row"><div><div class="eyebrow">'+t.category+'</div><h1>'+t.name+'</h1></div><span class="badge">Processed on your device</span></div><p class="intro">'+t.description+'</p><section class="workspace" aria-label="'+t.name+' workspace"><div class="toolbar"><strong>'+t.name+'</strong><div><button class="link-button" id="sample" data-value="'+esc(JSON.stringify(t.sample))+'">Load example</button><button class="link-button" id="clear">Clear</button></div></div>'+(t.id==='regex'?'<div class="extra"><label>Pattern<input id="pattern" value="\\d+" spellcheck="false"></label><label>Flags<input id="flags" value="g" spellcheck="false"></label></div>':'')+'<div class="editors"><div class="editor"><label for="input">'+(t.id==='uuid'?'Quantity':'Input')+'</label><textarea id="input" spellcheck="false" placeholder="'+(t.id==='uuid'?'Enter a quantity from 1 to 100':'Paste your input here…')+'">'+esc(t.sample)+'</textarea></div><div class="editor"><label for="output">Output</label><textarea id="output" readonly spellcheck="false" placeholder="Your result will appear here"></textarea></div></div><div class="actions">'+t.actions.map(a=>'<button class="action" data-action="'+a+'">'+a+'</button>').join('')+'<button class="link-button" id="copy">Copy result</button></div></section><div class="status" id="status" role="status" aria-live="polite">Ready. Use the example or paste your own input.</div><section class="explain"><div><h2>How to use '+t.name+'</h2><p>'+esc(t.how)+'</p></div><div><h2>Good to know</h2><p>'+esc(t.note)+'</p></div></section>';
await writeFile('dist/'+t.id+'.html',page(t.name,t.description+' Free, private, and browser-based.',body+renderGuide(t.id,tools,esc),t.id,t.id));}
const info={about:['About DevToolsHub','DevToolsHub brings ten common developer utilities into one fast, accessible workspace. It is maintained through the PrasannaArise/devtoolshub GitHub repository.','Tools run locally in your browser without an account. The site is a static application: formatting and conversion inputs are not uploaded to an application server.','Our first release focuses on practical daily tasks. Each tool explains its supported inputs and limitations. Please report reproducible bugs through the repository.'],contact:['Contact','Report a bug, suggest a tool, or ask a question through our GitHub repository. A GitHub account may be required to submit an issue.','Include the tool name, your browser, the steps you followed, and a minimal example that reproduces the problem. Remove tokens, credentials, and personal information before posting; GitHub issues are public.'],privacy:['Privacy Policy','Tool inputs and results are processed in your browser. This release does not upload your inputs, save them in browser storage, or include advertising, analytics, or tracking cookies. Closing or reloading a page clears its working inputs, subject to your browser’s own restoration behavior.','The hosting provider receives ordinary web requests and may process technical information such as IP addresses, user agents, and request logs to deliver and secure the site. Clipboard access is used only when you choose Copy result.','GitHub links take you to a separate service with its own privacy practices. Information you submit in public issues is publicly visible. If analytics, advertising, or data collection is added, this policy will be updated. For questions, use the Contact page.'],terms:['Terms of Use','DevToolsHub provides free developer utilities as available. Results may contain errors; review them before using them in production or making decisions that depend on their accuracy.','You are responsible for the data you enter and how you use results. Use the service lawfully. Do not rely on JWT decoding as signature verification, or raw SHA hashing for password storage.','Availability and tool behavior may change. The site provides no warranty of uninterrupted service or fitness for a particular purpose, to the extent permitted by applicable law. These terms do not limit rights that cannot be excluded under applicable law. Contact the maintainer through the Contact page.']};
for(const [id,[title,...paragraphs]]of Object.entries(info)){await writeFile('dist/'+id+'.html',page(title,title+' for DevToolsHub.','<article class="prose"><div class="eyebrow">DevToolsHub</div><h1>'+title+'</h1>'+paragraphs.map(p=>'<p>'+esc(p)+'</p>').join('')+(id==='about'||id==='contact'?'<p><a href="https://github.com/PrasannaArise/devtoolshub/issues">Open GitHub issues ↗</a></p>':'<p>Effective September 12, 2026.</p>')+'</article>',id));}
await writeFile('dist/404.html',page('Page not found','This page could not be found.','<h1>That page is not in the toolbox.</h1><p><a href="/">Browse all tools →</a></p>'));
await writeFile('dist/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40"><rect width="40" height="40" rx="8" fill="#2853df"/><text x="20" y="27" text-anchor="middle" font-size="22" font-family="monospace" fill="white">{}</text></svg>');
await writeFile('dist/robots.txt','User-agent: *\nAllow: /\n'+(origin?'Sitemap: '+origin.replace(/\/$/,'')+'/sitemap.xml\n':''));
if(origin)await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['',...tools.map(t=>t.id),...Object.keys(info)].map(path=>'<url><loc>'+esc(origin.replace(/\/$/,'')+'/'+path)+'</loc></url>').join('')+'</urlset>');
for(const file of ['style.css','app.mjs','core.mjs','worker.mjs'])await copyFile(file,'dist/'+file);
console.log('Built 15 pages and a 404 page.'+(origin?' Sitemap origin: '+origin:' Sitemap omitted until SITE_URL or VERCEL_PROJECT_PRODUCTION_URL is available.'));
