export const tools = [
['json','{}','JSON Formatter','Format, validate, and minify JSON.','Data','{"name":"DevToolsHub","tools":10,"free":true}', ['Format','Minify'], 'Paste JSON and choose Format for readable indentation or Minify for compact output. Invalid syntax is reported without changing your input.','JSON requires double-quoted keys and strings. Trailing commas and comments are not valid JSON. JavaScript number precision applies; quote large identifiers to preserve them.'],
['jwt','JWT','JWT Decoder','Inspect headers, claims, and expiration.','Security','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZW1vIiwiZXhwIjoxNzAwMDAwMDAwfQ.signature',['Decode'],'Paste a three-part JWT to read its header and payload. Expiration is compared with your device clock.','Decoding does not verify a signature or prove a token is trustworthy. Never use this result as an authorization decision. Encrypted JWTs are not supported.'],
['base64','64','Base64 Encoder / Decoder','Convert Unicode text to and from Base64.','Encoding','Hello, developer! 👋',['Encode','Decode'],'Encode text as UTF-8 Base64, or decode Base64 back to text. Unicode characters are supported.','Base64 is an encoding, not encryption. This tool expects UTF-8 text, not arbitrary binary files.'],
['uuid','#','UUID Generator','Generate random version 4 identifiers.','Generators','5',['Generate'],'Enter how many UUIDs you need, from 1 to 100. Each identifier uses your browser’s cryptographically secure random generator.','Version 4 UUIDs are suitable for identifiers. They are not a substitute for access controls or a complete authentication system.'],
['timestamp','◷','Unix Timestamp Converter','Switch between epoch time and UTC dates.','Data','1700000000',['Seconds to date','Milliseconds to date','Date to timestamp'],'Convert Unix seconds or milliseconds explicitly. For date input, use an ISO 8601 date with a time zone, such as 2023-11-14T22:13:20Z.','Unix time counts from January 1, 1970 UTC. Results include UTC and your local time. Explicit units avoid confusing seconds with milliseconds.'],
['url','%','URL Encoder / Decoder','Encode or decode a URL component.','Encoding','hello world & coffee ☕',['Encode','Decode'],'Encode a query parameter value or decode a percent-encoded component.','This uses encodeURIComponent, so reserved characters such as /, ?, and & are encoded. It is not intended to encode a complete URL. A plus sign stays a plus sign when decoding.'],
['cron','*','Cron Tester','Preview the next five runs in UTC.','Data','*/15 * * * *',['Next runs'],'Enter five fields: minute, hour, day of month, month, and day of week. Supports numbers, *, lists, ranges, and steps.','Uses UTC and standard five-field cron semantics. Sunday is 0 or 7. When both day fields are restricted, either may match. Names, macros, seconds, L, W, and # are not supported. Search is limited to five years.'],
['regex','.*','Regex Tester','Find JavaScript regex matches safely.','Text','DevToolsHub has 10 tools and 0 signups.',['Test'],'Enter a JavaScript regular expression without slash delimiters, set flags, and paste your test text. Results include match positions and capture groups.','Expressions run in a separate worker with a timeout. Extremely expensive patterns are stopped. Match output is capped at 1,000 results. Positions use JavaScript string offsets.'],
['sql','SQL','SQL Formatter','Tidy common SQL statements.','Text',"select id, name from users where active = true order by name;",['Format'],'Format common SELECT, INSERT, UPDATE, and DELETE statements into readable clauses. Quoted strings, identifiers, and comments are preserved.','This is a basic, dialect-neutral formatter, not a SQL parser or validator. Review complex procedural SQL before use. No query is executed.'],
['hash','SHA','Hash Generator','Calculate SHA-256, SHA-384, or SHA-512.','Security','Hello, developer!',['SHA-256','SHA-384','SHA-512'],'Paste text and choose a SHA algorithm to calculate its hexadecimal digest from UTF-8 bytes.','Hashes are one-way digests, not encryption. Raw SHA hashes are not suitable for password storage. A single changed character produces a different digest.']
].map(([id,icon,name,description,category,sample,actions,how,note])=>({id,icon,name,description,category,sample,actions,how,note}));
